# tests/test_entropy_estimators.R
#
# Reference validation and invariant checks for the D2 diversity estimators in
# `R/shannon_entropy.R` (Stage A2 of docs/ESTIMATOR_PIVOT_PLAN.md).
#
# Run from the repository root:
#     Rscript tests/test_entropy_estimators.R
#
# WHY THE EXPECTED VALUES ARE HARDCODED
#
# The 22 fixtures below were generated by evaluating `entropy_estimates()`
# against the CRAN `entropy` package version 1.3.2 — `entropy.empirical()`,
# `entropy.ChaoShen()` and `entropy.MillerMadow()`, all with `unit = "log2"` —
# and asserting agreement to within 1e-10. The largest observed absolute
# disagreement across all 22 cases and all three estimators was 1.26e-12, on
# `all_singletons_long`; every other case agreed to within 2.1e-14.
#
# That residual is the reference implementation's, not ours. `entropy::
# entropy.ChaoShen()` forms the Horvitz-Thompson inclusion probability as the
# naive `1 - (1 - pa)^n`, which loses significant digits when `pa` is small and
# `n` is large; `R/shannon_entropy.R` uses `-expm1(n * log1p(-pa))`, which does
# not. The two agree to 1e-12 at fixture scale and diverge in the reference's
# disfavour at Visium scale (pa ~ 1e-4, n ~ 1e4), which is the regime this
# project actually runs in.
#
# The `entropy` package was then dropped rather than pinned. It exists in this
# repository only as these numbers. Installing a CRAN package into the pinned
# conda environment to check ~40 lines of arithmetic once is the same trade D3
# already made when it rejected `ppcor` for the partial correlations, and the
# validation survives the removal because the expected values do. To re-verify
# after changing the kernel, install `entropy` into a throwaway library and
# regenerate; do not add it to `environment.yml`.
#
# No test framework either, for the same reason: this file needs base R and
# Matrix, both of which the pipeline already requires.

source("R/shannon_entropy.R")

TOL <- 1e-10

n_pass <- 0L
n_fail <- 0L

check <- function(label, ok, detail = "") {
  if (isTRUE(ok)) {
    n_pass <<- n_pass + 1L
  } else {
    n_fail <<- n_fail + 1L
    cat(sprintf("FAIL  %s%s\n", label, if (nchar(detail)) paste0("  [", detail, "]") else ""))
  }
}

check_close <- function(label, actual, expected, tol = TOL) {
  d <- max(abs(actual - expected))
  check(label, is.finite(d) && d <= tol, sprintf("max abs diff %.3e > %.1e", d, tol))
}

# ---------------------------------------------------------------------------
# 1. Reference fixtures: values verified against CRAN entropy 1.3.2
# ---------------------------------------------------------------------------

fixtures <- list(
  uniform_small = list(
    y = c(4L, 4L, 4L, 4L, 4L),
    expected = c(plugin =   2.32192809488736, chao_shen = 2.3490103402454898,
                 chao_shen_cwj = 2.3490103402454898, miller_madow = 2.4661975989762599)
  ),
  uniform_large = list(
    y = c(10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L,
      10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L,
      10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L, 10L),
    expected = c(plugin =   5.32192809488736, chao_shen = 5.3221408757892998,
                 chao_shen_cwj = 5.3221408757892998, miller_madow = 5.3922594781306996)
  ),
  all_singletons = list(
    y = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L),
    expected = c(plugin =                  3, chao_shen = 6.3358740626677896,
                 chao_shen_cwj = 6.3358740626677896, miller_madow = 3.6311790803889199)
  ),
  all_singletons_long = list(
    y = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L),
    expected = c(plugin = 5.6438561897747297, chao_shen =    11.398708140177,
                 chao_shen_cwj =    11.398708140177, miller_madow = 6.3507767598103202)
  ),
  two_singletons = list(
    y = c(1L, 1L),
    expected = c(plugin =                  1, chao_shen =   2.28571428571429,
                 chao_shen_cwj =   2.28571428571429, miller_madow = 1.3606737602222401)
  ),
  single_count_total_one = list(
    y = c(1L, 0L, 0L),
    expected = c(plugin =                  0, chao_shen =                  0,
                 chao_shen_cwj =                  0, miller_madow =                  0)
  ),
  single_gene_only = list(
    y = c(7L, 0L, 0L, 0L),
    expected = c(plugin =                  0, chao_shen =                  0,
                 chao_shen_cwj =                  0, miller_madow =                  0)
  ),
  dominant_plus_tail = list(
    y = c(500L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L),
    expected = c(plugin =  0.401421385468755, chao_shen = 0.64789880684349599,
                 chao_shen_cwj = 0.64789880684349599, miller_madow =  0.429165520870466)
  ),
  extreme_skew = list(
    y = c(10000L, 1L, 1L),
    expected = c(plugin = 0.0029455212318187001, chao_shen = 0.0047798281070099199,
                 chao_shen_cwj = 0.0047798281070099199, miller_madow = 0.00308976188777641)
  ),
  no_singletons = list(
    y = c(2L, 3L, 4L, 5L),
    expected = c(plugin =   1.92417435230044, chao_shen = 1.9992012236790699,
                 chao_shen_cwj = 1.9992012236790699, miller_madow = 2.0787488209671201)
  ),
  all_doubletons = list(
    y = c(2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L),
    expected = c(plugin =   3.32192809488736, chao_shen = 3.7816937724247501,
                 chao_shen_cwj = 3.7816937724247501, miller_madow = 3.6465344790873799)
  ),
  no_doubletons = list(
    y = c(1L, 3L, 5L, 7L),
    expected = c(plugin =   1.74899922306228, chao_shen =   1.89741882752401,
                 chao_shen_cwj =   1.89741882752401, miller_madow = 1.8842518831456201)
  ),
  one_off_degenerate = list(
    y = c(2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L),
    expected = c(plugin = 3.2776134368191201, chao_shen = 5.7823031732205701,
                 chao_shen_cwj = 5.6973033338432399, miller_madow = 3.8678068626373299)
  ),
  geometric_decay = list(
    y = c(64L, 32L, 16L, 8L, 4L, 2L, 1L),
    expected = c(plugin =   1.93356657653595, chao_shen =   1.97924840245518,
                 chao_shen_cwj =   1.97930290626589, miller_madow =   1.96764598695065)
  ),
  zeros_interleaved = list(
    y = c(0L, 5L, 0L, 0L, 3L, 0L, 1L, 0L, 1L),
    expected = c(plugin = 1.6854752972273299, chao_shen = 2.0908452024611801,
                 chao_shen_cwj = 2.0908452024611801, miller_madow =   1.90187955336068)
  ),
  poisson_shallow = list(
    y = c(0L, 0L, 0L, 0L, 1L, 0L, 2L, 2L, 1L, 3L, 1L, 0L, 0L, 0L, 1L, 0L, 0L,
      0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L,
      0L, 1L, 0L, 1L, 1L, 0L, 1L, 0L, 0L, 0L, 1L, 1L, 0L, 0L, 0L, 1L, 0L,
      1L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 1L),
    expected = c(plugin = 4.4946803684089103, chao_shen = 6.5337694170778802,
                 chao_shen_cwj = 6.5224612593999698, miller_madow =   5.08721583163116)
  ),
  poisson_moderate = list(
    y = c(1L, 1L, 1L, 1L, 0L, 1L, 0L, 4L, 1L, 5L, 2L, 2L, 3L, 1L, 0L, 1L, 2L,
      1L, 2L, 3L, 3L, 0L, 3L, 3L, 3L, 0L, 0L, 4L, 0L, 1L, 0L, 0L, 1L, 2L,
      1L, 1L, 2L, 1L, 1L, 0L, 3L, 1L, 1L, 0L, 0L, 2L, 2L, 2L, 3L, 1L, 0L,
      2L, 1L, 1L, 2L, 2L, 3L, 1L, 3L, 2L, 1L, 3L, 1L, 1L, 1L, 2L, 1L, 1L,
      4L, 0L, 0L, 1L, 0L, 2L, 0L, 0L, 2L, 3L, 0L, 1L, 2L, 1L, 1L, 1L, 1L,
      0L, 3L, 1L, 1L, 0L, 2L, 2L, 3L, 3L, 0L, 2L, 0L, 2L, 1L, 3L, 1L, 1L,
      2L, 1L, 4L, 3L, 2L, 3L, 2L, 1L, 0L, 2L, 1L, 2L, 1L, 0L, 2L, 1L, 1L,
      2L),
    expected = c(plugin = 6.3929390231844501, chao_shen = 7.0866337354903903,
                 chao_shen_cwj = 7.0922758068339702, miller_madow = 6.7804056913089097)
  ),
  poisson_deep = list(
    y = c(13L, 12L, 11L, 13L, 10L, 10L, 8L, 5L, 7L, 7L, 7L, 7L, 12L, 5L, 11L,
      13L, 10L, 14L, 10L, 9L, 9L, 8L, 11L, 14L, 3L, 10L, 8L, 9L, 6L, 7L,
      7L, 12L, 10L, 4L, 12L, 6L, 2L, 10L, 7L, 12L, 8L, 10L, 12L, 5L, 13L,
      8L, 10L, 6L, 9L, 6L, 7L, 9L, 9L, 6L, 5L, 10L, 8L, 5L, 7L, 4L, 5L, 9L,
      9L, 8L, 8L, 7L, 7L, 8L, 8L, 5L, 5L, 8L, 15L, 11L, 8L, 6L, 12L, 8L,
      9L, 7L, 7L, 11L, 10L, 12L, 10L, 12L, 5L, 10L, 8L, 11L, 13L, 6L, 10L,
      4L, 11L, 3L, 2L, 9L, 9L, 5L, 9L, 13L, 11L, 5L, 9L, 9L, 10L, 6L, 6L,
      3L, 10L, 11L, 7L, 8L, 7L, 11L, 6L, 4L, 12L, 11L, 12L, 11L, 3L, 2L,
      6L, 7L, 8L, 4L, 12L, 3L, 8L, 9L, 5L, 10L, 6L, 8L, 2L, 9L, 5L, 8L, 6L,
      8L, 8L, 6L, 5L, 9L, 7L, 6L, 10L, 3L, 6L, 10L, 9L, 13L, 6L, 12L, 5L,
      7L, 7L, 9L, 9L, 10L, 5L, 10L, 9L, 7L, 9L, 12L, 9L, 10L, 11L, 7L, 8L,
      2L, 6L, 10L, 7L, 7L, 7L, 8L, 5L, 8L, 8L, 8L, 8L, 7L, 8L, 4L, 6L, 6L,
      9L, 12L, 8L, 8L, 12L, 15L, 10L, 6L, 10L, 6L),
    expected = c(plugin = 7.5559882349710499, chao_shen = 7.5786820522000697,
                 chao_shen_cwj = 7.5786820522000697, miller_madow = 7.6438390039847901)
  ),
  nbinom_overdispersed = list(
    y = c(0L, 3L, 0L, 0L, 1L, 0L, 0L, 0L, 2L, 3L, 0L, 0L, 2L, 0L, 1L, 0L, 0L,
      1L, 0L, 10L, 0L, 0L, 0L, 0L, 0L, 11L, 9L, 0L, 0L, 1L, 7L, 0L, 2L, 2L,
      3L, 5L, 0L, 7L, 0L, 12L, 0L, 5L, 0L, 0L, 0L, 1L, 0L, 2L, 4L, 3L, 0L,
      1L, 0L, 3L, 3L, 0L, 2L, 1L, 21L, 1L, 8L, 3L, 0L, 6L, 3L, 0L, 9L, 13L,
      4L, 2L, 0L, 7L, 1L, 0L, 3L, 2L, 0L, 0L, 3L, 5L, 9L, 0L, 2L, 4L, 12L,
      17L, 0L, 2L, 22L, 2L, 18L, 1L, 0L, 1L, 1L, 1L, 5L, 0L, 0L, 0L, 0L,
      4L, 1L, 0L, 0L, 7L, 16L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 1L, 3L, 1L, 20L,
      1L, 0L, 2L, 0L, 1L, 0L, 3L, 0L, 0L, 0L, 0L, 4L, 2L, 2L, 1L, 0L, 0L,
      3L, 1L, 1L, 0L, 3L, 11L, 0L, 2L, 0L, 1L, 0L, 5L, 11L, 0L, 0L),
    expected = c(plugin = 5.7633806992631103, chao_shen = 5.9657508274981996,
                 chao_shen_cwj = 5.9664682105403903, miller_madow =   5.91194606947872)
  ),
  sparse_high_depth = list(
    y = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L,
      0L, 0L, 1L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L,
      1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 0L, 0L, 0L, 0L,
      0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 4000L, 2500L),
    expected = c(plugin = 0.99755053647437697, chao_shen =   1.01917431536244,
                 chao_shen_cwj =   1.01917431536244, miller_madow = 0.99965326781657504)
  ),
  half_singletons = list(
    y = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L,
      5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L),
    expected = c(plugin = 5.2938786114230796, chao_shen = 5.4805485267009804,
                 chao_shen_cwj = 5.4805485267009804, miller_madow = 5.5295188014349401)
  ),
  heavy_tail_realistic = list(
    y = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
      1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L,
      2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L,
      2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L,
      3L, 3L, 3L, 3L, 3L, 12L, 12L, 12L, 12L, 12L, 300L),
    expected = c(plugin = 4.5547307210471004, chao_shen = 5.4173498679043197,
                 chao_shen_cwj = 5.4177989916407796, miller_madow =   4.76934651225372)
  )
)

cat("--- 1. reference fixtures (CRAN entropy 1.3.2, tol 1e-10) ---\n")
for (nm in names(fixtures)) {
  f <- fixtures[[nm]]
  got <- entropy_estimates(f$y)
  check_close(sprintf("fixture %s", nm), got[names(f$expected)], f$expected)
}

# ---------------------------------------------------------------------------
# 2. Degenerate spots
# ---------------------------------------------------------------------------

cat("--- 2. degenerate spots ---\n")

# A spot with no counts at all. The CRAN reference returns NaN here (0/0 in the
# empirical frequencies); this project's convention, inherited from
# plugin_entropy_matrix(), is that an empty spot has zero entropy. Asserted so
# that the divergence from the reference is deliberate and recorded rather than
# discovered later in a spatial plot.
check_close("empty spot returns 0 for every estimator", entropy_estimates(rep(0, 5)), rep(0, 4))

# f1 == N (every observed gene a singleton) drives Good-Turing coverage to zero
# and the estimator to total degeneracy. The f1 := N - 1 substitution must keep
# every estimate finite. This is rare at Visium depths but occurs in the shallow
# tail, where an unguarded NaN would propagate silently.
for (nm in c("all_singletons", "all_singletons_long", "two_singletons", "single_count_total_one")) {
  check(sprintf("f1 == N guard keeps %s finite", nm), all(is.finite(entropy_estimates(fixtures[[nm]]$y))))
}

# f1 == 0 and f2 == 0 makes the Chao-Wang-Jost bracket 0/0; the limit is a zero
# correction (C = 1), not NaN.
check("CWJ 0/0 bracket resolves to C = 1", all(is.finite(entropy_estimates(c(5, 3, 4, 7)))))

# ---------------------------------------------------------------------------
# 3. Ordering invariants
# ---------------------------------------------------------------------------

cat("--- 3. ordering invariants ---\n")

fx <- do.call(rbind, lapply(fixtures, function(f) as.data.frame(as.list(entropy_estimates(f$y)))))

# Both corrections are upward, so these two hold by construction and a violation
# is a bug rather than a finding.
check("plugin <= miller_madow on every fixture", all(fx$miller_madow >= fx$plugin - TOL))
check("plugin <= chao_shen on every fixture", all(fx$chao_shen >= fx$plugin - TOL))
check("plugin <= chao_shen_cwj on every fixture", all(fx$chao_shen_cwj >= fx$plugin - TOL))

# miller_madow <= chao_shen is NOT a theorem, and this assertion pins that.
# Five of the 22 fixtures violate it — uniform_small, uniform_large,
# no_singletons, poisson_deep and half_singletons — which is every fixture with
# f1 = 0 plus one with a light singleton tail. Miller-Madow's correction depends
# only on K/N and so keeps growing with the observed support, while Chao-Shen's
# is driven by f1/N and vanishes when there are no singletons: with f1 = 0 the
# coverage estimate is 1 and Chao-Shen reduces to the plug-in value inflated
# only by the inclusion-probability denominator. An implementation that asserted
# the full plugin <= MM <= CS chain would report a bug on correct output.
n_mm_gt_cs <- sum(fx$chao_shen < fx$miller_madow - TOL)
check("miller_madow <= chao_shen is not universal (>= 1 counterexample)", n_mm_gt_cs >= 1,
      sprintf("counterexamples: %d", n_mm_gt_cs))
check("counterexamples are exactly the f1 == 0 / light-singleton cases", n_mm_gt_cs == 5,
      sprintf("expected 5, got %d", n_mm_gt_cs))

# check_entropy_ordering() must enforce the two real invariants and merely
# report the third.
ord <- check_entropy_ordering(fx)
check("check_entropy_ordering flags 3 invariants + 1 observation", nrow(ord) == 4 && sum(ord$Invariant) == 3)
check("check_entropy_ordering passes clean data", all(ord$N_Violations[ord$Invariant] == 0))
broken <- fx
broken$chao_shen[1] <- broken$plugin[1] - 1
check("check_entropy_ordering errors on a violated invariant",
      inherits(try(check_entropy_ordering(broken), silent = TRUE), "try-error"))

# Chao-Shen routinely exceeds log2(K), the maximum entropy of the *observed*
# support, because it estimates the entropy of the full distribution including
# unseen genes. Correct behaviour, asserted so it is not later mistaken for one.
K_fx <- vapply(fixtures, function(f) sum(f$y > 0), numeric(1))
check("chao_shen may exceed log2(K) (unseen-support estimation)", any(fx$chao_shen > log2(K_fx) + TOL))

# ---------------------------------------------------------------------------
# 4. Kernel behaviour on matrices
# ---------------------------------------------------------------------------

cat("--- 4. sparse kernel ---\n")

set.seed(23)
G <- 400L; S <- 60L
dense <- matrix(rpois(G * S, 0.4), nrow = G)
rownames(dense) <- paste0("G", seq_len(G))
colnames(dense) <- paste0("S", seq_len(S))
sp <- as(as(as(dense, "dMatrix"), "generalMatrix"), "CsparseMatrix")

est <- entropy_estimator_matrix(sp, return_stats = TRUE)

# The plug-in column must be bit-identical to plugin_entropy_matrix(), not
# merely close: `entropy_plugin` and the pipeline's `entropy_raw_plugin` column
# (D2) have to be the same number for the Stage A bake-off to compare the new
# estimators against the recorded baseline rather than against a re-derivation.
check("plugin identical to plugin_entropy_matrix (bitwise)",
      identical(unname(plugin_entropy_matrix(sp)), est$plugin))

# Per-column results must equal the single-vector path.
per_col <- t(vapply(seq_len(S), function(j) entropy_estimates(dense[, j]), numeric(4)))
check_close("matrix kernel agrees with per-column vector calls",
            as.matrix(est[, ENTROPY_ESTIMATORS]), per_col[, ENTROPY_ESTIMATORS])

# Blocking is an implementation detail and must not move any number.
old_opt <- getOption("entropy.block.nnz")
options(entropy.block.nnz = 50)
est_small <- entropy_estimator_matrix(sp)
options(entropy.block.nnz = 5e7)
est_big <- entropy_estimator_matrix(sp)
options(entropy.block.nnz = old_opt)
check("block size does not change results (nnz budget 50)",
      identical(est_small, est_big))
check_close("blocked result matches default budget",
            as.matrix(est_small), as.matrix(est[, ENTROPY_ESTIMATORS]))

# ---------------------------------------------------------------------------
# 5. Explicitly-stored zeros (the drop0 guard)
# ---------------------------------------------------------------------------

cat("--- 5. structural zeros ---\n")

# Seurat's subset() and the gene-universe filter leave structurally-stored
# explicit zeros behind. diff(@p) counts stored entries, not non-zero entries,
# so K, f1 and f2 are silently wrong without drop0() — and wrong in a way that
# biases the shallow spots the correction exists to rescue. This fixture makes
# the guard load-bearing: without it, K would be inflated by the injected zeros
# and Miller-Madow's (K-1)/(2N ln2) term would be inflated with it.
padded <- sp
zero_idx <- which(padded@x > 0)[seq(1, sum(padded@x > 0), by = 7)]
padded@x[zero_idx] <- 0
check("test fixture actually carries explicit zeros",
      any(padded@x == 0) && !identical(diff(padded@p), diff(Matrix::drop0(padded)@p)))

est_padded <- entropy_estimator_matrix(padded, return_stats = TRUE)
true_K <- as.numeric(Matrix::colSums(padded != 0))
check("K counts non-zero entries, not stored entries", identical(est_padded$K, true_K))
true_f1 <- as.numeric(Matrix::colSums(padded == 1))
true_f2 <- as.numeric(Matrix::colSums(padded == 2))
check("f1 counts singletons, unaffected by explicit zeros", identical(est_padded$f1, true_f1))
check("f2 counts doubletons, unaffected by explicit zeros", identical(est_padded$f2, true_f2))
check_close("estimates on a zero-padded matrix match the dropped one",
            as.matrix(est_padded[, ENTROPY_ESTIMATORS]),
            as.matrix(entropy_estimator_matrix(Matrix::drop0(padded))))

# ---------------------------------------------------------------------------
# 6. The counts assertion
# ---------------------------------------------------------------------------

cat("--- 6. counts assertion ---\n")

# f1 and f2 are counts of singleton and doubleton reads. On a normalized layer
# they are meaningless, and pointing an estimator at one is the category error
# that produced the entropy_spanorm_plugin defect recorded in D2. The kernel
# must refuse rather than return a plausible number.
normalized <- sp
normalized@x <- log2(normalized@x + 1)
check("non-integer matrix is rejected",
      inherits(try(entropy_estimator_matrix(normalized), silent = TRUE), "try-error"))

negative <- sp
negative@x[1] <- -1
check("negative values are rejected",
      inherits(try(entropy_estimator_matrix(negative), silent = TRUE), "try-error"))

check("check_counts = FALSE bypasses the assertion",
      !inherits(try(entropy_estimator_matrix(normalized, estimators = "plugin",
                                             check_counts = FALSE), silent = TRUE), "try-error"))

# ---------------------------------------------------------------------------

cat(sprintf("\n%d passed, %d failed\n", n_pass, n_fail))
if (n_fail > 0) quit(status = 1)
